[build]
  command = "npm run build -- --configuration production"
  publish = "dist/treetax"  # change if your output path is different

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


